#ifndef PROTOCOLOS_P_MAPA_H_
#define PROTOCOLOS_P_MAPA_H_

typedef enum {
	MORITE = 1,
	COORDENADA_POKENEST = 2,
	MENSAJE_OK = 3,
	ESTAS_EN_DEADLOCK = 4,
	TENES_TURNO = 5,
	CONFIRMACION_CAPTURA = 6,
	MOVETE = 7,
	DAR_MEDALLA = 8,
	MEN_OK=9,
	ESTAS_BLOQUEADO = 10,
	ESTAS_DESBLOQUEADO = 11,
	GANASTE = 12
} p_mensajes_mapa;

#endif /* PROTOCOLOS_P_MAPA_H_ */
